### PR TITLE
Added CORS helpers

### PR DESCRIPTION
**Pull request by filipw**
- introduced a bunch of classes allowing to configure CORs settings in `web.config` or `app.config` easily

Sample usage:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="cors" type="Climax.Web.Http.Cors.CorsSection, Climax.Web.Http" allowExeDefinition="MachineToApplication" />
  </configSections>
  <cors>
    <corsPolicies>
      <add name="foo" origins="http://foo.com;http://test.com" headers="x-api-rate" methods="GET;POST" />
    </corsPolicies>
  </cors>
</configuration>
```

### CODE REVIEW

**Comment by tcrosen** [comment]
Can you throw the sample usage into the README?

**Comment by nahidf** [comment]
@filipw why not comma separated for origins, as `EnableCorsAttribute` accept comma separated too?
just asking

**Comment by filipw** [comment]
it's already removed https://github.com/climax-media/honda-models-lib/pull/155/files#diff-906f95d5c8a55fabf953544cd75d6e3eR58

**Comment by hajarniamehr** [comment]
@filipw link to a private repo from a public repo. Not cool :cop:

**Comment by filipw** [comment]
lol wrong issue :smile:

**Pull request merged**
